# Generated by Django 2.1.4 on 2018-12-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_titulo', models.CharField(default='', max_length=200, verbose_name='Título')),
                ('doc_descricao', models.CharField(default='', max_length=300, verbose_name='Descrição')),
                ('doc_path', models.CharField(default='', max_length=600, verbose_name='Caminho')),
                ('doc_dt_cad', models.DateField(verbose_name='Data Cadastro')),
                ('doc_usuario', models.CharField(default='', max_length=300, verbose_name='Quem Cadastrou')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_nome', models.CharField(default='', max_length=200, verbose_name='nome')),
                ('fase_descricao', models.CharField(default='', max_length=400, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sis_nome', models.CharField(default='', max_length=200, verbose_name='nome')),
                ('sis_descricao', models.CharField(default='', max_length=400, verbose_name='descrição')),
                ('sis_setor_cliente', models.CharField(default='', max_length=300, verbose_name='setor Solicitante')),
                ('sis_dt_criacao', models.DateField(verbose_name='data Criação')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_dt_inicio', models.DateField(verbose_name='data Início')),
                ('sf_dt_termino', models.DateField(verbose_name='data Término')),
                ('sf_situacao', models.CharField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, max_length=1)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemasfvs.Fase')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemasfvs.Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_nome', models.CharField(default='', max_length=200, verbose_name='nome')),
                ('st_descricao', models.CharField(default='', max_length=400, verbose_name='descrição')),
                ('st_cor', models.CharField(default='', max_length=20, verbose_name='cor')),
            ],
        ),
        migrations.AddField(
            model_name='sistema',
            name='fases',
            field=models.ManyToManyField(through='sistemasfvs.SistemaFase', to='sistemasfvs.Fase'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='status_cod_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemasfvs.Status'),
        ),
        migrations.AddField(
            model_name='documento',
            name='sistema_cod_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemasfvs.Sistema'),
        ),
    ]
