# Generated by Django 2.1.4 on 2018-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasfvs', '0002_documento_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='doctos_files/'),
        ),
        migrations.AlterField(
            model_name='sistemafase',
            name='sf_situacao',
            field=models.CharField(choices=[('1', 'Ativo'), ('0', 'Inativo')], default='1', max_length=1),
        ),
    ]
