# Generated by Django 2.1.4 on 2018-12-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasfvs', '0003_auto_20181227_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemafase',
            name='sf_dt_inicio',
            field=models.DateField(verbose_name='data de Início'),
        ),
        migrations.AlterField(
            model_name='sistemafase',
            name='sf_dt_termino',
            field=models.DateField(verbose_name='data de Término'),
        ),
        migrations.AlterField(
            model_name='sistemafase',
            name='sf_situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='situação'),
        ),
    ]
