# Generated by Django 2.1.4 on 2018-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasfvs', '0004_auto_20181227_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemafase',
            name='sf_situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Finalizada', 'Finalizada')], default='Ativo', max_length=12, verbose_name='situação'),
        ),
    ]
