# Generated by Django 2.1.4 on 2019-02-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasfvs', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doc_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
