# Generated by Django 2.1.4 on 2019-03-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasfvs', '0009_auto_20190214_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('perfil', 'Pode alterar dados do perfil de usuário'),)},
        ),
    ]
