# Generated by Django 2.1.4 on 2019-01-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('area_descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atv_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('atv_descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro_nome', models.CharField(max_length=100, verbose_name='bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_tipo_entidade', models.CharField(max_length=1, verbose_name='tipo de entidade')),
                ('ent_cpf_cnpj', models.CharField(max_length=100, verbose_name='CPF/CNPJ')),
                ('ent_nome_razao', models.CharField(max_length=300, verbose_name='nome / Razão Social')),
                ('ent_fantasia', models.CharField(max_length=200, verbose_name='nome Fantasia')),
                ('ent_insc_estadual', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('ent_insc_municipal', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('ent_cnes', models.CharField(max_length=100, verbose_name='CNES (Estabelecimentos de Saúde)')),
                ('ent_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('ent_complemento', models.CharField(max_length=300, verbose_name='Complemento')),
                ('ent_endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('ent_fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('ent_fax', models.CharField(max_length=15, verbose_name='Fax')),
                ('ent_email', models.CharField(max_length=200, verbose_name='E-mail')),
                ('ent_dt_inicio_func', models.CharField(max_length=10, verbose_name='Data de Início do Funcionamento')),
                ('ent_pasta_num', models.CharField(max_length=200, verbose_name='Número da Pasta')),
                ('ent_obj_contrato_social', models.CharField(max_length=500, verbose_name='Objetivo Contrato Social')),
                ('ent_observacoes', models.CharField(max_length=500, verbose_name='Observações')),
                ('ent_rg', models.CharField(max_length=20, verbose_name='RG')),
                ('ent_orgao_exp', models.CharField(max_length=100, verbose_name='Órgão Expedidor')),
                ('ent_dt_expedicao', models.CharField(max_length=10, verbose_name='Data de Expedição')),
                ('ent_registro_conselho', models.CharField(max_length=100, verbose_name='Registro no Conselho')),
                ('ent_especializacao', models.CharField(max_length=200, verbose_name='Especialização')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Entidadeatividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Entidade')),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esc_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('esc_descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_nome', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('for_descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Escolaridade')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mun_nome', models.CharField(max_length=100, verbose_name='município')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_nome', models.CharField(max_length=100, verbose_name='natureza Jurídica / Dependência Administrativa')),
                ('nat_descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_nome', models.CharField(max_length=100, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Subatividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Area')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Atividade')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Pais'),
        ),
        migrations.AddField(
            model_name='entidadeatividade',
            name='subatividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Subatividade'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='escolaridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Escolaridade'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='formacao_profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Formacao'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Municipio'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='natureza_juridica_dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Natureza'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Municipio'),
        ),
    ]
