# Generated by Django 2.1.4 on 2019-01-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacao',
            name='for_descricao',
        ),
        migrations.RemoveField(
            model_name='subatividade',
            name='area',
        ),
    ]
