# Generated by Django 2.1.4 on 2019-01-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0002_auto_20190103_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'permissions': (('pais_list', 'Pode listar país'), ('pais_create', 'Pode cadastrar país'), ('pais_update', 'Pode editar país'), ('pais_view', 'Pode ver país'), ('pais_delete', 'Pode deletar país'))},
        ),
    ]
