# Generated by Django 2.1.4 on 2019-01-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0004_auto_20190107_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='ent_cpf_cnpj',
        ),
    ]
