# Generated by Django 2.1.4 on 2019-01-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0005_remove_entidade_ent_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='ent_cnpj',
            field=models.CharField(default='', max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_cpf',
            field=models.CharField(default='', max_length=20, verbose_name='CPF'),
        ),
    ]
