# Generated by Django 2.1.4 on 2019-01-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0007_auto_20190110_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='devisa.Municipio'),
        ),
    ]
