# Generated by Django 2.1.4 on 2019-01-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0008_auto_20190110_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(blank=True, default='Selecione um Município', on_delete=django.db.models.deletion.CASCADE, to='devisa.Municipio'),
        ),
    ]
