# Generated by Django 2.1.4 on 2019-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0010_auto_20190110_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='ent_nome_razao',
            field=models.CharField(max_length=300, verbose_name='nome / Razão Social'),
        ),
    ]
