# Generated by Django 2.1.4 on 2019-01-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0011_auto_20190110_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Bairro'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_dt_inicio_func',
            field=models.CharField(max_length=10, verbose_name='Data de Início do Funcionamento'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_endereco',
            field=models.CharField(max_length=300, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Municipio'),
        ),
    ]
