# Generated by Django 2.1.4 on 2019-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0012_auto_20190110_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='ent_numero',
            field=models.CharField(default='0', max_length=6, verbose_name='Endereço'),
        ),
    ]
