# Generated by Django 2.1.4 on 2019-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0014_auto_20190110_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='ent_cep',
            field=models.CharField(max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_fone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
