# Generated by Django 2.1.4 on 2019-01-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0016_auto_20190110_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='ent_cnpj',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cpf',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_dt_expedicao',
            field=models.CharField(blank=True, max_length=20, verbose_name='Data de Expedição'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_dt_inicio_func',
            field=models.CharField(max_length=20, verbose_name='Data de Início do Funcionamento'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_tipo_entidade',
            field=models.CharField(max_length=2, verbose_name='tipo de entidade'),
        ),
    ]
