# Generated by Django 2.1.4 on 2019-01-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0017_auto_20190110_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='escolaridade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devisa.Escolaridade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidade',
            name='formacao_profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Formacao'),
        ),
    ]
