# Generated by Django 2.1.4 on 2019-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0018_auto_20190110_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='ent_cep',
            field=models.CharField(default='', max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_dt_inicio_func',
            field=models.CharField(default='', max_length=20, verbose_name='Data de Início do Funcionamento'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_endereco',
            field=models.CharField(default='', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_nome_razao',
            field=models.CharField(default='', max_length=300, verbose_name='nome / Razão Social'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_numero',
            field=models.CharField(default='', max_length=6, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_tipo_entidade',
            field=models.CharField(default=1, max_length=2, verbose_name='tipo de entidade'),
        ),
    ]
