# Generated by Django 2.1.4 on 2019-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0020_auto_20190110_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='ent_cnes',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='CNES (Estabelecimentos de Saúde)'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cnpj',
            field=models.CharField(blank=True, default='', max_length=30, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_complemento',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cpf',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_dt_expedicao',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Data de Expedição'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_email',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_especializacao',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Especialização'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_fantasia',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_fax',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_fone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_insc_estadual',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_insc_municipal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_obj_contrato_social',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Objetivo Contrato Social'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_observacoes',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_orgao_exp',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Órgão Expedidor'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_pasta_num',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Número da Pasta'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_registro_conselho',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Registro no Conselho'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_rg',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='RG'),
        ),
    ]
