# Generated by Django 2.1.4 on 2019-01-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0022_auto_20190111_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='ent_cpf',
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
