# Generated by Django 2.1.4 on 2019-01-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0025_auto_20190111_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devisa.Bairro'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_cep',
            field=models.CharField(default='', max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_cnes',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='CNES (Estabelecimentos de Saúde)'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_complemento',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_cpf',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_dt_expedicao',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Data de Expedição'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_dt_inicio_func',
            field=models.CharField(default='', max_length=20, verbose_name='Data de Início do Funcionamento'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_email',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_endereco',
            field=models.CharField(default='', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_especializacao',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Especialização'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_fantasia',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='nome Fantasia'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_fax',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_fone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_insc_estadual',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_insc_municipal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_numero',
            field=models.CharField(default='', max_length=6, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_obj_contrato_social',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Objetivo Contrato Social'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_observacoes',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_orgao_exp',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Órgão Expedidor'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_pasta_num',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Número da Pasta'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_registro_conselho',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Registro no Conselho'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='ent_rg',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='escolaridade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devisa.Escolaridade'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='formacao_profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devisa.Formacao'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devisa.Municipio'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='natureza_juridica_dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devisa.Natureza'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cnpj',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_tipo_entidade',
            field=models.CharField(default=1, max_length=2, verbose_name='tipo de entidade'),
        ),
    ]
