# Generated by Django 2.1.4 on 2019-01-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0026_auto_20190111_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Bairro'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cnpj',
            field=models.CharField(default='', max_length=30, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cpf',
            field=models.CharField(default='', max_length=20, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='escolaridade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Escolaridade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='formacao_profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Formacao'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Municipio'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='natureza_juridica_dependencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Natureza'),
        ),
    ]
