# Generated by Django 2.1.4 on 2019-01-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0028_auto_20190111_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entidadeatividade',
            new_name='EntidadeSubatividade',
        ),
        migrations.AlterModelOptions(
            name='entidadesubatividade',
            options={'permissions': (('entsub_list', 'Pode listar subatividades do estabelecimento'), ('entsub_create', 'Pode incluir subatividades do estabelecimento'), ('entsub_delete', 'Pode deletar subatividades do estabelecimento'))},
        ),
        migrations.AlterField(
            model_name='entidade',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Bairro'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cnpj',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ent_cpf',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='escolaridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Escolaridade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='formacao_profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Formacao'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Municipio'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='natureza_juridica_dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devisa.Natureza'),
        ),
    ]
