# Generated by Django 2.1.4 on 2019-01-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0030_auto_20190118_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeSubatividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Entidade')),
                ('subatividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devisa.Subatividade')),
            ],
            options={
                'permissions': (('entsub_list', 'Pode listar subatividades do estabelecimento'), ('entsub_create', 'Pode incluir subatividades do estabelecimento'), ('entsub_delete', 'Pode deletar subatividades do estabelecimento')),
            },
        ),
    ]
