# Generated by Django 2.1.4 on 2019-01-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0033_auto_20190128_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadesubatividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_tecnico', to='devisa.Entidade'),
        ),
        migrations.AlterField(
            model_name='entidadesubatividade',
            name='subatividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subatividade', to='devisa.Subatividade'),
        ),
    ]
