# Generated by Django 2.1.4 on 2019-01-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0034_auto_20190128_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesubatividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_tecnico', to='devisa.Entidade'),
        ),
    ]
