# Generated by Django 2.1.4 on 2019-01-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0037_auto_20190128_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadesubatividade',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='entidadesubatividade',
            name='responsavel_tecnico',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_tecnico', to='devisa.Entidade'),
        ),
    ]
