# Generated by Django 2.1.4 on 2019-01-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0038_auto_20190128_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estabelecimento', to='devisa.Entidade')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade', to='devisa.Entidade')),
            ],
        ),
    ]
