# Generated by Django 2.1.4 on 2019-01-31 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0040_auto_20190131_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesubatividade',
            name='terceirizado',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceirizado', to='devisa.Entidade'),
        ),
    ]
