# Generated by Django 2.1.4 on 2019-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0046_auto_20190214_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureza',
            name='nat_categoria',
            field=models.CharField(choices=[('1', 'Estabelecimento Comercial'), ('2', 'Unidade de Estabelecimento'), ('3', 'Empresa Terceirizada'), ('4', 'Profissional Liberal'), ('5', 'Profissional Autônomo'), ('6', 'Responsável Legal'), ('7', 'Responsável Técnico')], default='1', help_text='Esta opção só aparecerá nesta categoria de cadastro', max_length=1, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='natureza',
            name='nat_descricao',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
    ]
