# Generated by Django 2.1.4 on 2019-03-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0047_auto_20190218_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeClasseproducaoWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=14, verbose_name='estabelecimento')),
                ('classe_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classe_producaows', to='devisa.Classeproducao')),
            ],
        ),
        migrations.CreateModel(
            name='EntidadeFormaproducaoWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=14, verbose_name='estabelecimento')),
                ('forma_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forma_producaows', to='devisa.Formaproducao')),
            ],
        ),
        migrations.CreateModel(
            name='EntidadeSubatividadeWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=14, verbose_name='estabelecimento')),
                ('subatividade', models.CharField(max_length=20, verbose_name='estabelecimento')),
                ('terceirizado', models.CharField(max_length=14, verbose_name='terceirizada')),
                ('responsavel_tecnico', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_tecnicows', to='devisa.Entidade')),
            ],
        ),
    ]
