# Generated by Django 2.1.4 on 2019-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0048_entidadeclasseproducaows_entidadeformaproducaows_entidadesubatividadews'),
    ]

    operations = [
        migrations.AddField(
            model_name='subatividade',
            name='sub_cnae',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Código CNAE'),
        ),
    ]
